Add typings
mapbox/mapbox-gl-supported pull request #40
Opened 2021-10-18 19:25 UTC by HarelM

This PR adds typings to this library.
It might not be complete as I have reverse engineered the code...

2021-10-22 08:38 UTC, mourner requested changes

2021-10-22 08:38 UTC, mourner commented on index.d.ts
> +declare type IsSuppotredOptions = {
Nit: typo here

2021-10-22 09:18 UTC, HarelM commented on index.d.ts
> +declare type IsSuppotredOptions = {
My bad... fixed...

2021-10-22 10:27 UTC, mourner approved these changes

2021-10-22 10:27 UTC, merged

2021-10-24 11:46 UTC, HarelM commented
Thanks for taking the time to review and merge this! please let me know when a new version is available.

2021-10-25 10:18 UTC, mourner commented
Released as v2.0.1.

2021-10-25 10:46 UTC, HarelM commented
Thanks!! [vector-tile-js](https://github.com/mapbox/vector-tile-js) is the last one :-)